### ISSUE TITLE
A deploy is not started when a previous deploy has failed

### ISSUE THREAD

**Issue by larseen** [kolonialno/kraken-deploy#4]
It should mark is_done for both `error` and `failure` 
https://github.com/kolonialno/kraken-deploy/blob/main/kraken/github/types.py#L36

Also, we should probably always create the deployment and then just queue them?
We could leverage argo-workflows queueing by having the same name on the workflow and just running one at the time?

https://github.com/argoproj/argo-workflows/blob/master/examples/synchronization-wf-level.yaml

**Comment by ljodal** [comment]
If anything I guess we could make this an option, but for some projects it doesn't make sense to try the next commit if a deploy has failed. Rather someone should manually inspect to figure out what went wrong, maybe revert a commit and then manually start a deploy of that.

**Comment by thor** [comment]
Not planning to implement this in kraken or in deploy-action: manual intervention is what'll be the primary focus.
